---

- include_tasks: prep.yaml

# A kubernetes (or OpenShift) host and an API key must be set.
# We will either have authenticated against an OpenShift server
# or the AWX kubernetes credentials will have injected suitable
# values for the K8S_AUTH_HOST and K8S_AUTH_API_KEY environment variables.
# Either way the ansible variables 'k8s_auth_host' and
# 'k8s_auth_api_key' will have been set.
- name: Assert authentication
  assert:
    that:
    - k8s_auth_host|length > 0
    - k8s_auth_api_key|length > 0

- name: Delete loader volume
  block:

  - name: Get expected namespace
    k8s_info:
      kind: Namespace
      name: "{{ ccd_namespace }}"
    register: namespace_info

  - name: Assert namespace exists
    assert:
      that: namespace_info.resources|length > 0
      fail_msg: Namespace '{{ ccd_namespace }}' does not exist

  - name: Delete loader volume
    k8s:
      state: absent
      definition: "{{ lookup('template', 'pvc-loader.yaml.j2') }}"
      wait: yes
      wait_timeout: "{{ wait_timeout }}"

  module_defaults:
    group/k8s:
      host: "{{ k8s_auth_host }}"
      api_key: "{{ k8s_auth_api_key }}"
